name = "AbstractGUI"
uuid = "796b4d30-d51d-4664-90d1-7cd8560850fa"
authors = ["Cédric Belmant"]
version = "0.1.0"

[deps]
GeometryExperiments = "1147bd75-18e1-436d-adda-d58e854f897d"
WindowAbstractions = "e18202ca-4a7d-4de8-b056-fa6bbd7de157"

[compat]
WindowAbstractions = "0.2, 0.3"
julia = "1.5"

[extras]
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Meshes"]
